runtime: python
env: flex
entrypoint: gunicorn -b :$PORT manage:app

runtime_config:
  python_version: 3

env_variables:
  SQLALCHEMY_DATABASE_URI: >-
    postgresql+psycopg2://teck:password@/smuqueue?host=/cloudsql/smuqueue:asia-southeast1:smuqueue

beta_settings:
  cloud_sql_instances: smuqueue:asia-southeast1:smuqueue